"""Command headers as the manual spells them. Generated; do not edit.

Written by ``migrations/scripts/generate_simulator_aliases.py`` from the
literals this driver sends. The capitals mark where each mnemonic's short form
ends, which is what lets the simulator accept ``SYST:ERR?`` as well as
``SYSTEM:ERROR?``, the way a real instrument does.

Headers containing a runtime substitution are not recorded: they are not
headers until the value is filled in.
"""

from __future__ import annotations

__all__ = ["CANONICAL_HEADERS"]

CANONICAL_HEADERS: tuple[str, ...] = (
    "*ESR",
    "*IDN",
    "*LRN",
    "*RCL",
    "*RST",
    "*SAV",
    "*TRG",
    "AM:DEPTh",
    "AM:INTernal:FREQuency",
    "AM:INTernal:FUNCtion",
    "AM:SOURce",
    "AM:STATe",
    "BURSt:GATE:POLarity",
    "BURSt:INTernal:PERiod",
    "BURSt:MODE",
    "BURSt:NCYCles",
    "BURSt:PHASe",
    "BURSt:STATe",
    "CAL",
    "CAL:COUNt",
    "CAL:SECure:CODE",
    "CAL:SECure:STATe",
    "CAL:SETup",
    "CAL:STRing",
    "CAL:VALue",
    "DATA",
    "DATA:ATTRibute:AVERage",
    "DATA:ATTRibute:CFACtor",
    "DATA:ATTRibute:POINts",
    "DATA:ATTRibute:PTPeak",
    "DATA:CATalog",
    "DATA:COPY",
    "DATA:DELete",
    "DATA:DELete:ALL",
    "DATA:NVOLatile:CATalog",
    "DISPlay",
    "DISPlay:TEXT",
    "DISPlay:TEXT:CLEar",
    "FM:DEViation",
    "FM:INTernal:FREQuency",
    "FM:INTernal:FUNCtion",
    "FM:SOURce",
    "FM:STATe",
    "FREQuency",
    "FREQuency:STARt",
    "FREQuency:STOP",
    "FSKey:FREQuency",
    "FSKey:INTernal:RATE",
    "FSKey:SOURce",
    "FSKey:STATe",
    "FUNCtion",
    "FUNCtion:PULSe:DCYCle",
    "FUNCtion:PULSe:HOLD",
    "FUNCtion:PULSe:TRANsition",
    "FUNCtion:PULSe:WIDTh",
    "FUNCtion:RAMP:SYMMetry",
    "FUNCtion:SQUare:DCYCle",
    "FUNCtion:USER",
    "MARKer",
    "MARKer:FREQuency",
    "MEMory:STATe:VALid",
    "OUTPut",
    "OUTPut:LOAD",
    "OUTPut:POLarity",
    "PM:DEViation",
    "PM:INTernal:FREQuency",
    "PM:INTernal:FUNCtion",
    "PM:SOURce",
    "PM:STATe",
    "PULSe:PERiod",
    "PWM:DEViation",
    "PWM:INTernal:FREQuency",
    "PWM:INTernal:FUNCtion",
    "PWM:SOURce",
    "PWM:STATe",
    "SWEep:SPACing",
    "SWEep:STATe",
    "SWEep:TIME",
    "SYSTem:COMMunicate:GPIB:ADDRess",
    "SYSTem:COMMunicate:LAN:AUTOip",
    "SYSTem:COMMunicate:LAN:IPADdress",
    "SYSTem:COMMunicate:LAN:LIPaddress",
    "SYSTem:COMMunicate:LAN:MAC",
    "SYSTem:COMMunicate:LAN:MEDiasense",
    "SYSTem:COMMunicate:LAN:NETBios",
    "SYSTem:COMMunicate:LAN:TELNet:PROMpt",
    "SYSTem:COMMunicate:LAN:TELNet:WMESsage",
    "SYSTem:ERRor",
    "SYSTem:KLOCk",
    "SYSTem:KLOCk:EXCLude",
    "TRIGger:SLOPe",
    "TRIGger:SOURce",
    "VOLTage",
    "VOLTage:OFFSet",
    "VOLTage:UNIT",
)
