"""Command headers as the manual spells them. Generated; do not edit.

Written by ``migrations/scripts/generate_simulator_aliases.py`` from the
literals this driver sends. The capitals mark where each mnemonic's short form
ends, which is what lets the simulator accept ``SYST:ERR?`` as well as
``SYSTEM:ERROR?``, the way a real instrument does.

Headers containing a runtime substitution are not recorded: they are not
headers until the value is filled in.
"""

from __future__ import annotations

__all__ = ["CANONICAL_HEADERS"]

CANONICAL_HEADERS: tuple[str, ...] = (
    "*ESR",
    "*IDN",
    "*RCL",
    "*SAV",
    "*TRG",
    "CALCulate:AVERage:AVERage",
    "CALCulate:AVERage:CLEar",
    "CALCulate:AVERage:COUNt",
    "CALCulate:AVERage:MAXimum",
    "CALCulate:AVERage:MINimum",
    "CALCulate:AVERage:PTPeak",
    "CALCulate:AVERage:SDEViation",
    "CALCulate:DB:REFerence",
    "CALCulate:DBM:REFerence",
    "CALCulate:FUNCtion",
    "CALCulate:LIMit:LOWer",
    "CALCulate:LIMit:UPPer",
    "CALCulate:STATe",
    "CALibration",
    "CALibration:ADC",
    "CALibration:COUNt",
    "CALibration:LFRequency",
    "CALibration:LFRequency:ACTual",
    "CALibration:SECure:CODE",
    "CALibration:SECure:STATe",
    "CALibration:STORe",
    "CALibration:STRing",
    "CALibration:VALue",
    "DATA:COPY",
    "DATA:DATA",
    "DATA:DELete",
    "DATA:LAST",
    "DATA:POINts",
    "DATA:REMove",
    "DISPlay",
    "DISPlay:TEXT",
    "DISPlay:TEXT:CLEar",
    "FETCh",
    "FUNCtion",
    "MEMory:NSTates",
    "MEMory:STATe:CATalog",
    "MEMory:STATe:DELete",
    "MEMory:STATe:DELete:ALL",
    "MEMory:STATe:NAME",
    "MEMory:STATe:RECall:AUTO",
    "MEMory:STATe:RECall:SELect",
    "MEMory:STATe:VALid",
    "READ",
    "ROUTe:TERMinals",
    "SAMPle:COUNt",
    "SAMPle:COUNt:PRETrigger",
    "SAMPle:SOURce",
    "SAMPle:TIMer",
    "SYSTem:BEEPer:STATe",
    "SYSTem:COMMunicate:LAN:AUTOip:STATe",
    "SYSTem:COMMunicate:LAN:BSTatus",
    "SYSTem:COMMunicate:LAN:CONTrol",
    "SYSTem:COMMunicate:LAN:DDNS",
    "SYSTem:COMMunicate:LAN:DHCP",
    "SYSTem:COMMunicate:LAN:DNS",
    "SYSTem:COMMunicate:LAN:DOMain",
    "SYSTem:COMMunicate:LAN:GATEway",
    "SYSTem:COMMunicate:LAN:HISTory",
    "SYSTem:COMMunicate:LAN:HISTory:CLEar",
    "SYSTem:COMMunicate:LAN:HOSTname",
    "SYSTem:COMMunicate:LAN:IPADdress",
    "SYSTem:COMMunicate:LAN:KEEPalive",
    "SYSTem:COMMunicate:LAN:LIPaddress",
    "SYSTem:COMMunicate:LAN:MAC",
    "SYSTem:COMMunicate:LAN:MEDiasense",
    "SYSTem:COMMunicate:LAN:NETBios",
    "SYSTem:COMMunicate:LAN:SMASk",
    "SYSTem:COMMunicate:LAN:TELNet:PROMpt",
    "SYSTem:COMMunicate:LAN:TELNet:WMESsage",
    "SYSTem:ERRor",
    "SYSTem:LANguage",
    "TEMPerature:TRANsducer:THERmistor:TYPE",
    "TEMPerature:TRANsducer:TYPE",
    "TRIGger:COUNt",
    "TRIGger:DELay",
    "TRIGger:DELay:AUTO",
    "TRIGger:LEVel",
    "TRIGger:SLOPe",
    "TRIGger:SOURce",
    "UNIT:TEMPerature",
    "VOLTage:IMPedance:AUTO",
)
