"""Production-oriented Python driver for NGI N83624 battery/cell simulators."""

from __future__ import annotations

from .channel import N83624Channel
from .driver import N83624CellSimulator
from .exceptions import (
    BusyError,
    CommandError,
    CommunicationError,
    DeviceError,
    ExecutionError,
    HeartbeatError,
    InterlockError,
    N83624Error,
    ProtocolError,
    RecoveryError,
    SafetyError,
    SessionStateError,
    TimeoutError,
    ValidationError,
)
from .models import (
    CaptureRate,
    ChannelConfiguration,
    ChannelLimits,
    ChannelStatus,
    CommunicationObservation,
    CurrentRange,
    DriverSafetyPolicy,
    FaultSimulationMode,
    HeartbeatConfig,
    InstrumentLimits,
    LanConnectionType,
    Language,
    Measurement,
    NullBenchInterlock,
    OutputMode,
    OutputState,
    ReconnectPolicy,
    RetryPolicy,
    SequenceStep,
    SessionState,
    SocStep,
)
from .transports import SerialTransport, TcpTransport, Transport, UdpTransport, udp_channel

__version__ = "0.1.0"

__all__ = [
    "BusyError",
    "CaptureRate",
    "ChannelConfiguration",
    "ChannelLimits",
    "ChannelStatus",
    "CommandError",
    "CommunicationError",
    "CommunicationObservation",
    "CurrentRange",
    "DeviceError",
    "DriverSafetyPolicy",
    "ExecutionError",
    "FaultSimulationMode",
    "HeartbeatConfig",
    "HeartbeatError",
    "InstrumentLimits",
    "InterlockError",
    "LanConnectionType",
    "Language",
    "Measurement",
    "N83624CellSimulator",
    "N83624Channel",
    "N83624Error",
    "NullBenchInterlock",
    "OutputMode",
    "OutputState",
    "ProtocolError",
    "RecoveryError",
    "ReconnectPolicy",
    "RetryPolicy",
    "SafetyError",
    "SerialTransport",
    "SequenceStep",
    "SessionState",
    "SessionStateError",
    "SocStep",
    "TcpTransport",
    "TimeoutError",
    "Transport",
    "UdpTransport",
    "ValidationError",
    "udp_channel",
]
